name: Build and Push Node App Docker Image

on: 
  push: 
    branches:
      - main  # Run on every push to main branch

jobs:
  build-and-push:
    runs-on: self-hosted 

    steps:
      # Step 1: Checkout the code
      - name: Clone Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      # Step 5: Run Docker Container (optional test step)
      - name: Run Container
        run: |
          docker run -d -p 3000:3000 --name my-node-container ${{ secrets.DOCKER_USERNAME }}/node-app:latest
          sleep 10
          docker logs my-node-container

      # Step 6: Push Docker image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest
